version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  configure-role-arn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      
      
workflows:
  aws-cli:
    jobs:
      - configure-role-arn
