# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference


version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_Access_Key_ID
          aws-secret-access_key: AWS_Secret_Aceess_key
          aws-session-token: AWS_session_token
          
workflows:
  aws-cli:
    jobs:
      - aws-cli-cred-setup:
          context: aws
