# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference


version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access_key: AWS_SECRET_ACCESS_KEY
          aws-session-token: AWS_SESSION_TOKEN
          
workflows:
  aws-cli:
    jobs:
      - aws-cli-cred-setup:
          context: aws
