# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
executors:
  j13:
    docker:
      - image: 'cimg/openjdk:13.0'
  j15:
    docker:
      - image: 'cimg/openjdk:15.0'
orbs:
  maven: circleci/maven@1.1
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          matrix:
            parameters:
              executor:
                - j13
                - j15

